

//GET http://localhost:5000/appointment/received-appointment?doctorid=d004
//Content-Length: application/json


//POST https://final-year-backend-35ph.onrender.com/api/v1/user/register
//Content-Type: application/json
//Content-Length: application/json
//
//{
//    "name":"Emmauel Adane",
//    "email":"a",
//    "password":"a",
//    "phone":"a"
//}

//POST http://localhost:5000/api/v1/consultant/registerhealthworker
//Content-Type: application/json
//
//{
//    "name":"",
//    "email":"",
//    "password":"",
//    "healthWorkerId":""
//}

POST http://localhost:5000/api/v1/user/register
Content-Type: application/json

{
    "name":"Emmanuel Adane Bosea", 
    "email":"emmanueladane52@gmail.com",
    "password":"B125@sah" ,
    "phone":"0546506783"
}

//getting the data of users in a conversation 
//GET http://localhost:5000/api/v1/chat/get_conversation:12345